### ISSUE TITLE
Bug due to some lingering evaluations

### ISSUE THREAD

**Issue by sebffischer** [dgkf/R#115]
I don't fully understand this yet, but sometimes some expressions seem to get evaluated after the last expression is evaluated, which then changes the return value.

```R
y <- {
  f <- fn(x) {x; null}
  x <- 1
  f(x = {x <- 2})
  x == 2
}

print(y)
#> 2
```

**Comment by dgkf** [comment]
Interesting. Definitely a bug! I just tried to simplify the example as much as possible, and this also produces the same erroneous result:

```r
> y <- {
:   f <- fn(param) { param }
:   f({ x <- 2 })
:   x == 1
: }
[1] false

> y <- {
:   f <- fn(x) { x }
:   f({ x <- 2 })
:   x == 1
: }
[1] 2
```

**Comment by dgkf** [comment]
Here's another one that might help pinpoint it:

```r
> y <- {
:   f <- fn(...) { null }
:   f(x = {x = 2})
:   x
: }
Error: object 'x' not found
```

I _think_ this might be related to lazy argument evaluation, where expressions in arguments are stored as closures. Although this is actually consistent with R!

```r
# real R
> f <- function(...) NULL
> f(x = { x <- 10 })
NULL
> x
Error: object 'x' not found
```

There's still an issue with having to force the closure, but I was surprised to see that R has a similar constraint. This is necessary to support many non-standard-evaluation behaviors, but something I hadn't anticipated.
