### ISSUE TITLE
print does not work in the demo repl

### ISSUE THREAD

**Issue by sebffischer** [dgkf/R#118]
The reply will always print the returned value, but calling `print()` directly is ignored. 

![Screenshot 2024-04-07 at 15-35-50 dgkf_R](https://github.com/dgkf/R/assets/20975557/b90273eb-43fd-4b5a-84cc-77ba3ed3545b)

**Comment by dgkf** [comment]
Ooof, you're right. I never even attempt to manage "output"... I haven't even investigated where the results of `println!()` would go in `wasm`-land. 

It looks like it's not exactly trivial to just capture `println!` in `wasm`, so this will take some investigating to figure out the right way to proceed.
