### ISSUE TITLE
Implement paste()

### ISSUE THREAD

**Issue by armenic** [dgkf/R#13]
As a follow-up of https://github.com/dgkf/R/pull/8#issuecomment-1569351812 maybe it is good time to implement `paste()`.

References #5 

@dgkf, do I understand correctly that we want to implement `paste()` as a primitive (written in Rust?) function, similar to `q()`?

I am also curious whether we will ever write functions in R or port them over from R?

**Comment by dgkf** [comment]
Great question!

> do I understand correctly that we want to implement paste() as a primitive (written in Rust?) function

Quick answer first - then more discussion:

Yep, that's what I was thinking. If your goal is to use this as an opportunity to implement some R concepts in rust, I would say go for it.

---

But this also brings up a good question about what our goals should be. My original goal was to use this little exercise to learn some rust and experiment with what I thought would be cool enhancements to R, but the project has gotten a bit of momentum now and if others want to see it as a practical replacement, we might need to go back to the drawing board in terms of how we approach the problem.

A more pragmatic approach would be to call into R's internal implementations to bootstrap a new implementation, allowing for a slow migration from C to rust. In this case, we can find R's [`paste` code here](https://github.com/wch/r-source/blob/trunk/src/main/paste.c). Probably this would involve first building a rust interface to the `libR` shared library.

Interfacing with R's internals would be a big shift in the project, though. It would mean that the rust representations of R objects need to be more direct analogs of the C implementations, or at least add a translation layer to and from rust representations.

**Comment by armenic** [comment]
Thanks Doug!

Since I want to learn Rust, I will go with pure Rust for now :) I can not believe that paste() is 757 lines of code in C, let's see if Rust can do it with a shorter logic. 

I was thinking to grab the unit test from R source code and I could not find a test for paste(), [my search](https://github.com/search?q=repo%3Awch%2Fr-source+paste+path%3A%2F%5Etests%5C%2F%2F&type=code&p=3).
