### ISSUE TITLE
use a different hash function for environments

### ISSUE THREAD

**Issue by sebffischer** [dgkf/R#138]
The default hash function in rust is SipHash, which is a cryptographic hash function to avoid ddos attacks. But we don’t really care about this in the context her (I guess). As retrieving elements from the environment happens so often it might be worthwhile to pick a faster hash function.

**Comment by sebffischer** [comment]
Maybe we can use this one: https://github.com/rust-lang/hashbrown (the HashMap in std actually uses this implementation but with a different hash function)

**Comment by dgkf** [comment]
Awesome find! I never even considered this as an option. Yeah, I’d say we can definitely choose something other than the default here.
