### ISSUE TITLE
Implementing `sum()`

### ISSUE THREAD

**Issue by dgkf** [dgkf/R#15]
Primitives are implemented as special function names and evaluate code in lower-level code (`rust`). If a function of that name isn't found in the environment, we look through the known primitives to find the code to execute for that function name. This is a simplification of R's primitive calling, but it's sufficient for us to move forward with building up a standard library. 

There are a few primitives that are already in place and will give a good template for implementing new ones. Primitives are matched against a known mapping in `primitive()`. We'll need to add a `"sum" => Some(Box::new(primitive_sum))` branch here:

https://github.com/dgkf/R/blob/117d4dffa5f01344ba2a546dedc6b8e360f33686/src/builtins.rs#L771-L778

Then the next step is to implement 

```rust
pub fn primitive_sum(args: ExprList, env: &mut Environment) -> EvalResult {
  // for each arg (Expr) in args (ExprList)
  //   try eval expression in calling environment (`env.eval(value)?`)
  //   try coerce value to numeric (example of this coercion in `primitive_c`)
  //   add sum of elements to a total sum
}
```

I'm fine ignoring the `na.rm` parameter for now... this might be a design quirk of R that we leave in the past.

**Comment by sebffischer** [comment]
What exactly do you mean with the second part of this sentence?

> I'm fine ignoring the na.rm parameter for now... this might be a design quirk of R that we leave in the past.

**Comment by dgkf** [comment]
> What exactly do you mean with the second part of this sentence / why is it something that should be left in the past?

It's just a colorful way of saying we can deviate from R's `sum()` behavior and not add the `na.rm` parameter. 

There are two reasons for this. First, it makes it easier to implement! Second, I'm assuming the `na.rm` argument was introduced in R to avoid an intermediate vector allocation when doing `sum(na.omit(x))`. I'd like iterators/generators to eventually be part of the core design, so there wouldn't be any intermediate vector created anyways. We're not there yet, but there's no reason to waste time implementing things that should be handled by the language.

**Comment by sebffischer** [comment]
This can be closed, I am not sure why it didn’t get closed automatically when merging the PR as I mentioned this issue
