### ISSUE TITLE
Binary releases?

### ISSUE THREAD

**Issue by eitsupi** [dgkf/R#34]
Can you upload binaries to the GitHub release so we can try this out immediately?
I have done such CI setup on other repositories and may be able to help.

**Comment by dgkf** [comment]
Sure- that sounds reasonable to me. Thanks for the suggestion! I’ve been meaning to get some CI set up - especially now that we are starting to hone in on a better testing strategy. If you can link to a repo that does something similar, that would help move it along faster.

**Comment by dgkf** [comment]
No release builds yet - but I did get a wasm version set up so you can now try it out in your browser at https://dgkf.github.io/R/

**Comment by dgkf** [comment]
@eitsupi 

>  I have done such CI setup on other repositories and may be able to help.

Would you be able to link me to a repo where you set this up and also provide some instructions on how you would plan to use them? Is it simply to have a file you can download and run or are there other parts of a workflow that this would help support?

**Comment by eitsupi** [comment]
Sorry I haven't been able to do this.

This is what I actually set:
https://github.com/PRQL/prql/blob/27b70c5acab8837898221ad11ace320ab0743dba/.github/actions/build-prqlc/action.yaml
Builds and uploads are done for each PR, so anyone can immediately see the changes made in the PR.
https://github.com/PRQL/prql/blob/27b70c5acab8837898221ad11ace320ab0743dba/.github/workflows/tests.yaml#L556-L596

As a side note, cross-compilation for Linux is easier with [cross](https://github.com/cross-rs/cross).
The release workflow of this repository may be helpful.
https://github.com/datafuselabs/bendsql/blob/adb31ed7e4980a244a0f353ac2ab8fe2c1d3d126/.github/workflows/release.yml

**Comment by dgkf** [comment]
@eitsupi Thanks for those resources! I ended up using the `helix` project as a basis and adapted their setup (just because it's a bit simpler than the setup for `prql`). 

It also has previews in PRs and releases on tags, which I think is a good fit. 

For now just publishing `x86` linux binaries, but will enable a few others before merge. You can check out the first preview binaries here:

https://github.com/dgkf/R/actions/runs/6477863673?pr=63

Is there anything more that you'd be looking for in such a feature?

**Comment by eitsupi** [comment]
@dgkf Thanks! I left a comment on #63.

**Comment by dgkf** [comment]
Thanks for all your help @eitsupi! We now have binaries in PR artifacts and [on release](https://github.com/dgkf/R/releases/tag/v0.3.2) 🎉

**Comment by eitsupi** [comment]
Awesome, thanks for working on this!
