### ISSUE TITLE
Function definition accepts multiple ellipsis arguments

### ISSUE THREAD

**Issue by sebffischer** [dgkf/R#74]
The following parses (and also works), but should not I think. 

```r
function(..., ...) list(...)
```

**Comment by dgkf** [comment]
Yeah, agreed - this should raise an error.

**Comment by sebffischer** [comment]
I have a question about how to solve this.
I tried to just make the [`parse_pairlist`](https://github.com/dgkf/R/blob/3f6e34cec869d62848783912748c7315b0ab5a14/src/parser/core.rs#L179-L199) function return an error when there is more than one ellipsis argument.
This is then propagated by [this line](https://github.com/dgkf/R/blob/3f6e34cec869d62848783912748c7315b0ab5a14/src/parser/core.rs#L242). So [`parse_primary`](https://github.com/dgkf/R/blob/3f6e34cec869d62848783912748c7315b0ab5a14/src/parser/core.rs#L71) then returns the `Err` variant. 

From these lines: https://github.com/dgkf/R/blob/3f6e34cec869d62848783912748c7315b0ab5a14/src/parser/core.rs#L137-L140 I also assumed that this is the right approach to throw a parsing error.

However, if I then spin up the repl and try to evaluate `function(..., ...) 1`, the parser does not stop parsing and I can't evaluate the expression.

Can you maybe tell me how to approach this correctly?

**Comment by sebffischer** [comment]
In general there needs to me more assertions on the contents of the pairlist, i.e. stuff like

```r
function(x, 1) x 
```

should also be captured

**Comment by dgkf** [comment]
The `pairlist` parsing is also used for lists, and we still want this to work:

```r
f <- function(...) list(..., ...)
f(1, 2)
# list(1, 2, 1, 2)
```

Even though a function with multiple ellipsis is weird, I think the expression itself should parse without error (treating ellipsis like any other variable name), but then throw an error when we go to evaluate the expression.

The code where the expression gets evaluated into objects happens over in [src/lang.rs](https://github.com/dgkf/R/blob/a27970b2d23b0b11873db476cf1045a24a6d898b/src/lang.rs#L908-L933) and we can implement a quick test like this:

```rs
            Expr::Function(formals, body) => {
                Err(Error::Other("aborting function evaluation!".to_string()).into())
                // Ok(Obj::Function(formals, *body, self.env().clone()))
            },
```

I'd suggest breaking this out into a a separate function such as `check_formals(formals: ExprList) -> Result<ExprList, Signal>` and then this snippet just becomes:

```rs
            Expr::Function(formals, body) => {
                Ok(Obj::Function(check_formals(formals)?, *body, self.env().clone()))
            },
```
