### ISSUE TITLE
Suggestion: Support `_` as digit seperator

### ISSUE THREAD

**Issue by sebffischer** [dgkf/R#97]
I.e. 

```
1_000_000
```

vs.

```
1000000
```

**Comment by dgkf** [comment]
Great idea. One of many things I love about julia/rust, and I see no reason not to follow this trend to improve the readability of code.

**Comment by sebffischer** [comment]
Great! I think this will be a great first issue for me to work on the grammar, so I would love to give it a go when I have the time :)

**Comment by sebffischer** [comment]
This is now available!
